### ISSUE TITLE
Support android and ios targets

### ISSUE THREAD

**Issue by RezMike** [sergeshustoff/dikt#4]
I'm trying to use dikt in Kotlin Multiplatform Mobile project. But gradle shows this error during sync when I add dikt-runtime library:
```
Failed building KotlinMPPGradleModel
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find dikt-runtime-1.0.0-alpha2-samplessources.jar (com.github.sergeshustoff.dikt:dikt-runtime:1.0.0-alpha2).
Searched in the following locations:
    https://jitpack.io/com/github/sergeshustoff/dikt/dikt-runtime/1.0.0-alpha2/dikt-runtime-1.0.0-alpha2-samplessources.jar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound
    ...
```
I suppose it's because of the lack of support for android and ios targets.

**Comment by sergeshustoff** [comment]
I think it's because jitpack builds artifacts only for Linux+js+jvm, but not for mac and windows. It will be fixed when I move to maven central or something similar and build for all platforms

**Comment by sergeshustoff** [comment]
But you can build it yourself to maven local for all needed platforms

**Comment by sergeshustoff** [comment]
@RezMike It should be fixed in 1.0.0-alpha5. It's now published to maven central (gradle plugin published to gradle plugin repo).
Check release notes, there're a lot of changes since alpha2

**Comment by RezMike** [comment]
@sergeshustoff thank you for the information, I will try new version this Friday and give you feedback

**Comment by sergeshustoff** [comment]
Tried to use in iOS sample, seems it works
